---
title: "`r params$model`"
author: "Marvin Ludwig"
date: '2022-02-10'
params:
  model: "modelname"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    orientation: rows
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

modelname = params$model
```


```{r}
source("setup.R")


load_model = function(modelname){
    m = list(
        modelname = modelname,
        model = readRDS(file.path(modelname, "rfmodel.RDS")),
        aoa = readRDS(file.path(modelname, "aoa.RDS")),
        results = raster::stack(file.path(modelname, "results/pred_di_aoa.grd")),
        geodist = readRDS(file.path(modelname, "training_geodist.RDS")),
        featuredist = readRDS(file.path(modelname, "training_featuredist.RDS")),
        folds = readRDS(file.path(modelname, "folds.RDS"))
    )
    return(m)
}



m = load_model(modelname)
```

Row
----

### Training Samples + Folds

```{r}
t = st_read("data/training_samples.gpkg", quiet = TRUE)
t$fold = m$folds

plot(t[,"fold"])
```



### DI Map

```{r}
tm_shape(m$aoa$DI)+
    tm_raster()
```



Row
----

### Distances Geo Space

```{r}
plot_distance(m$geodist)
```

### Distance Feature Space

```{r}
plot_distance(m$featuredist)
```




### AOA

```{r}
tm_shape(m$aoa$AOA)+
    tm_raster( style = "cat")
```

Row
----

### Global Validation

```{r}
CAST::global_validation(m$model)
```

### DI Plot

```{r}
plot(m$aoa)
```

